name: Cypress Tests for 91

on: [push]
jobs:
  cypress-run: ubuntu-latest
  steps: 
   - name: Checkout
     uses: actions/checkout@v2
   - name: Cypress run
     uses: cypress-io/github-actions@v2
     with:
       build: npm run build
       start: npm start
